language: java
cache:
  directories:
  - $HOME/.m2
sudo: false
jdk:
  - oraclejdk8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CARGO_DAEMON_WEBAPP_VERSION=1.4.16
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./target/.
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script:
  - mvn cargo:daemon-start
  - mvn test -f itest/pom.xml
