sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/cargo-daemon

install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sh ./startup-cargo-daemon.sh

script:
  - mvn -U package cargo:daemon-start
  - mvn -U test -f itest/pom.xml
  - mvn -U clean test jacoco:report coveralls:report
