sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
cache:
  directories:
    - $HOME/.m2
    - $HOME/cargo-daemon
install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sh ./startup-cargo-daemon.sh

script:
  - mvn -U package cargo:daemon-start -Djava.security.egd=file:/dev/urandom -Dcargo.jvmargs="-Xms512m -Xmx1024m -Djava.security.egd=file:/dev/urandom"
  - mvn -U test -f itest/pom.xml -Djava.security.egd=file:/dev/urandom
